import type { Metadata } from 'next'


import { ReactNode } from 'react'
import ContainerComponent from '@/app/components/wrappComponent/page'





export const metadata: Metadata = {
    title: 'Hỗ trợ',
    description: 'Generated by create next app',
}

interface Iprops {
    children: ReactNode

}

export default function Layout({ children }: Iprops) {
    return (
        <ContainerComponent>
            {children}
        </ContainerComponent>
    )
}
