export interface DataApi {
  created_at: string;
  gia_thue: number;
  gui_xac_nhan_khach: number;
  han_hop_dong: string;
  han_thanh_toan: string;
  id: number;
  id_cong_viec: null | number;
  id_ctv_sale: null | number;
  id_nguoi_dan: null | number;
  id_nhan_vien_ky: number;
  id_nhan_vien_sale: null | number;
  id_phieu_chi: null | number;
  id_phong: number;
  id_user_tao: number;
  id_user_tao_coc: number | null;
  id_user_tao_thue: number;
  link_video: null | string;
  list_gia: string;
  ly_do_huy_giu: null | string;
  ma_hop_dong: string;
  ngay_gui: string;
  ngay_het_han: string;
  ngay_ky: string;
  ngay_tao_hoa_don: string;
  ngay_thanh_ly: null | string;
  ngay_xac_nhan: string;
  otp: string;
  phone_gui: string;
  phong: {
    avatar: string;
    ban_cong: number;
    bep: number;
    bep_chung: number;
    bon_rua_chen: number;
    cua_so: number;
    dang_tin_tro4u: number;
    dang_tin_uthang: number;
    dien_tich: null | number;
    facebook_1: null | string;
    facebook_2: null | string;
    gac: number;
    ghi_chu: string;
    gia: number;
    gia_coc: null | number;
    gia_dien: number;
    gia_khac: number;
    gia_may_giat: number;
    gia_nuoc: number;
    gia_rac: number;
    gia_the: number;
    gia_wifi: number;
    gia_xe: number;
    gio_giac: null | string;
    giuong: number;
    id: number;
    id_nha: number;
    id_user: number;
    is_quan_ly: number;
    khoa_van_tay: number;
    lau: number;
    loai: string;
    may_giat: number;
    may_giat_chung: number;
    may_lanh: number;
    nem: number;
    ngay_bao_tra: null | string;
    ngay_cho_thue: string;
    ngay_giu_cho: string;
    ngay_trong: null | string;
    ngay_trong_phat: null | string;
    noi_that: null | string;
    noi_that_khac: null | string;
    nuoc_nong: number;
    nuoi_thu_cung: number;
    san_phoi: number;
    show_ctv: number;
    ten: string;
    thang_may: number;
    thumbnail: null | string;
    tien_ich: null | string;
    tinh_trang: string;
    tinh_trang_san_pham: string;
    tivi: number;
    tollet: number;
    tu_lanh: number;
    tu_lanh_chung: number;
    tu_quan_ao: number;
    updated_at: string;
    website_1: null | string;
    website_2: null | string;
    nha: {
      id: number;
      id_user: number;
      nhom: string;
      id_khu: number;
      tinh_trang: string;
      ten: string;
      so_lau: number;
      id_tinh_thanh: number;
      id_quan_huyen: number;
      id_phuong_xa: number;
      dia_chi: string;
      avatar: string;
      quan_ly_1: string;
      quan_ly_2: string | null;
      link_gioi_thieu: string;
      vi_tri: string;
      video: string | null;
      gia_dien: number;
      gia_nuoc: number;
      gia_xe: number;
      gia_rac: number;
      gia_wifi: number;
      gia_may_giat: number;
      gia_the: number;
      gia_khac: number;
      ngay_tinh_so_lieu: string | null;
      del: number;
      created_at: string;
      updated_at: string;
    }
  };
  so_lan_gui_otp: number;
  tai_san_ban_giao: null | string;
  thanh_toan: string;
  theo_doi: string;
  thoi_gian_coc: string;
  thoi_gian_thue: string;
  tien_coc: number;
  tien_phu_phi: number;
  tinh_trang_hop_dong: string;
  tra_coc: number;
  updated_at: string;
  video_checkin: null | string;
  video_checkout: null | string;
  zns_canh_bao_du_no_lan_1: number;
  zns_canh_bao_du_no_lan_2: number;
}
export interface LoginApi {
  status: string
  data: DataApi[]
}