import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ContainerComponent2 from '@/app/components/wrappComponent2/page'
import { ReactNode } from 'react'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Hợp đồng',
    description: 'Generated by create next app',
}

interface Iprops {
    children: ReactNode

}

export default function Layout({ children }: Iprops) {
    return (
        <ContainerComponent2>
            {children}
        </ContainerComponent2>
    )
}
