import type { Metadata } from 'next'


import { ReactNode } from 'react'
import ContainerComponent from '@/app/components/wrappComponent/page'





export const metadata: Metadata = {
    title: 'Báo sự cố',
    description: 'Generated by create next app',
}

interface Iprops {
    children: ReactNode

}

export default function Layout({ children }: Iprops) {
    return (

        children

    )
}
